name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3.17.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          
      - name: Test with pytest
        run: # Program make a simple calculator



# This function adds two numbers
def add(x, y):
    return x + y



# This function subtracts two numbers
def subtract(x, y):
    return x - y



# This function multiplies two numbers
def multiply(x, y):
    return x * y



# This function divides two numbers
def divide(x, y):
    return x / y




print("Select operation.")

print("1.Add")
print("2.Subtract")
print("3.Multiply")
print("4.Divide")



while True:
    # take input from the user
    choice = input("Enter choice(1/2/3/4): ")



   # check if choice is one of the four options
    if choice in ('1', '2', '3', '4'):
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))



       if choice == '1':
            print(num1, "+", num2, "=", add(num1, num2))



       elif choice == '2':
            print(num1, "-", num2, "=", subtract(num1, num2))



       elif choice == '3':
            print(num1, "*", num2, "=", multiply(num1, num2))



       elif choice == '4':
            print(num1, "/", num2, "=", divide(num1, num2))
        
        # check if user wants another calculation
        # break the while loop if answer is no
        next_calculation = input("Let's do next calculation? (yes/no): ")
        if next_calculation == "no":
          break
    
    else:
        print("Invalid Input")
